import { Geist, Geist_Mono } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import DrawerComponent from "@/components/drawer";
import AppBarComponent from "@/components/app-bar";
import { Box, Button, Toolbar } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { AppProvider } from "@/context/app";
import SpinnerComponent from "@/components/spinner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              height: "100vh",
            }}
          >
            <AppBarComponent />
            <Box sx={{ display: "flex", flexGrow: 1 }}>
              <DrawerComponent />
              <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
                <Toolbar />
                <CssBaseline />
                {children}
              </Box>
            </Box>
            <SpinnerComponent />
          </Box>
        </AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
